let userRequests = [
  {
    id: 1,
    status: 0,
    agency_name: "الأحمد",
    type: 2,
    guide_name: null,
    request_date: "2024-03-18",
    style: "color: orange; font-weight: 700",
  },
  {
    id: 2,
    status: 0,
    guide_name: "الأحمد",
    type: 1,
    agency_name: null,
    request_date: "2024-03-18",
    style: "color: orange; font-weight: 700",
  },
  {
    id: 3,
    status: 1,
    guide_name: "الأحمد",
    type: 1,
    agency_name: null,
    request_date: "2024-03-18",
    style: "color: green; font-weight: 700",
  },
  {
    id: 4,
    status: -1,
    agency_name: "الأحمد",
    type: 2,
    guide_name: null,
    request_date: "2024-03-18",
    style: "color: red; font-weight: 700",
  },
  {
    id: 5,
    status: 0,
    guide_name: "الأحمد",
    type: 1,
    agency_name: null,
    request_date: "2024-03-18",
    style: "color: orange; font-weight: 700",
  },
  {
    id: 6,
    status: 1,
    agency_name: "الأحمد",
    type: 2,
    guide_name: null,
    request_date: "2024-03-18",
    style: "color: green; font-weight: 700",
  },
  {
    id: 7,
    status: -1,
    guide_name: "الأحمد",
    type: 1,
    agency_name: null,
    request_date: "2024-03-18",
    style: "color: red; font-weight: 700",
  },
  {
    id: 8,
    status: 1,
    guide_name: "الأحمد",
    type: 1,
    agency_name: null,
    request_date: "2024-03-18",
    style: "color: green; font-weight: 700",
  },
  {
    id: 9,
    status: -1,
    agency_name: "الأحمد",
    type: 2,
    guide_name: null,
    request_date: "2024-03-18",
    style: "color: red; font-weight: 700",
  },
];
